export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';

//Auth
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_AUTH_FAILED = 'LOGIN_USER_AUTH_FAILED';
export const LOGIN_UNVERIFIED_USER_FAILED = 'LOGIN_UNVERIFIED_USER_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';

//Profile
export const PROFILE_UPDATED = 'PROFILE_UPDATED';
export const PROFILE_LOGOUT = 'PROFILE_LOGOUT';