export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';

//Auth
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_AUTH_FAILED = 'LOGIN_USER_AUTH_FAILED';
export const LOGIN_UNVERIFIED_USER_FAILED = 'LOGIN_UNVERIFIED_USER_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';

//Profile
export const PROFILE_UPDATED = 'PROFILE_UPDATED';
export const PROFILE_LOGOUT = 'PROFILE_LOGOUT';

//Sign-Up
export const SIGNUP_UPDATE = 'SIGNUP_UPDATED';
export const SIGNUP_SUBMIT_STEP = 'SIGNUP_SUBMIT_STEP';
export const SIGNUP_STEP1_SUCCESS = 'SIGNUP_STEP1_SUCCESS';
export const SIGNUP_STEP1_ERROR = 'SIGNUP_STEP1_ERROR';
export const SIGNUP_STEP2_SUCCESS = 'SIGNUP_STEP2_SUCCESS';
export const SIGNUP_STEP2_ERROR = 'SIGNUP_STEP2_ERROR';
export const SIGNUP_STEP3_SUCCESS = 'SIGNUP_STEP3_SUCCESS';
export const SIGNUP_STEP3_ERROR = 'SIGNUP_STEP3_ERROR';
export const SIGNUP_STEP4_SUCCESS = 'SIGNUP_STEP4_SUCCESS';
export const SIGNUP_STEP4_ERROR = 'SIGNUP_STEP4_ERROR';